Fix template_ws
j3soon/ros2-agv-essentials pull request #13
Opened 2023-10-13 13:40 UTC by YuZhong-Chen

- Update gitignore.
- Change the mounting folder inside docker-compose.

2023-10-21 15:48 UTC, j3soon requested changes
Please modify the following according to our previous private discussion:
- update README, and
- add 3 extensions

2023-10-27 04:35 UTC, j3soon requested changes

2023-10-27 04:35 UTC, j3soon commented on template_ws/.gitignore
I just learned yesterday about the "Leading slash" syntax of `.gitignore`:

> A leading `**` followed by a slash means match in all directories. For example, `**/foo` matches file or directory `foo` anywhere, the same as pattern `foo`.

> The pattern `doc/frotz` and `/doc/frotz` have the same effect in any .gitignore file. In other words, a leading slash is not relevant if there is already a middle slash in the pattern.

I believe it is better to be explicit and change the file to:

```
docker/cache
.vscode
/build
/install
/log
```

to avoid unintentionally ignoring folders in a nested hierarchy. (and also ignore the `log` folder)

Ref: https://git-scm.com/docs/gitignore

2023-10-27 04:35 UTC, j3soon commented on template_ws/README.md
> +- `docker/docker-compoase.yaml`
typo: `docker-compoase.yaml` -> `docker-compose.yaml`

2023-10-27 04:35 UTC, j3soon commented on template_ws/README.md
> +    - Change the `image_name` and `comtainer_name`.
typo: `comtainer_name` -> `container_name`

2023-10-27 04:35 UTC, j3soon commented on template_ws/README.md
Since we will create other workspaces based on this template. Do you think it would be better to add a create workspace script in `/scripts/create_workspace.sh`? The script is simple:

1. Prompt the user to provide the workspace name
2. Copy the template directory `cp template_ws xxx_ws`
3. Replace the `template_ws` name with `sed` in several files.

What do you think?

<hr>

Some details when writing the script:
- Use the `-e` flag to abort on error:

  https://github.com/j3soon/docker-ros-kobuki/blob/17f93d26d15c584295f7485b6c28433de735034a/docker-compose.sh#L1

- Make sure to copy files relative to the script path (instead of the current working directory) to prevent behavior difference when calling `./scripts/create_workspace.sh` and `./create_workspace.sh` in different directories.

  https://github.com/j3soon/docker-ros-kobuki/blob/17f93d26d15c584295f7485b6c28433de735034a/docker-compose.sh#L3

  Reference: https://stackoverflow.com/a/246128

  based on the `$DIR` variable above, you'll want to `cp "$DIR/../template_ws" "$DIR/../${WS_NAME}_ws"`

2023-10-27 06:57 UTC, j3soon commented on template_ws/docker/docker-compose.yaml
Also, change this filename to `compose.yaml`.

Ref: https://docs.docker.com/compose/compose-file/03-compose-file/

2023-10-27 07:53 UTC, j3soon commented on template_ws/.gitignore
We also need to unignore `.gitkeep`:

```
.vscode
/build
/install
/log
docker/cache/*
!docker/cache/.gazebo
docker/cache/.gazebo/*
!docker/cache/.gazebo/.gitkeep
```

Ref: https://github.com/j3soon/ros2-agv-essentials/blob/ee9ee64df9238e1cd43223146f41b4471b492a57/rtabmap_ws/.gitignore

2023-10-27 15:22 UTC, YuZhong-Chen commented on template_ws/README.md
I believe it will be useful. I'll try to implement it. XD

2023-10-28 09:10 UTC, YuZhong-Chen commented on template_ws/README.md
I have finished the script, you may see it in my last commit. However,  when I attempt to replace all strings of "template_ws" with the new workspace name, I encounter the issue that the docker image name is "ros2-template-ws," and it can't be directly replaced using `sed`.

For easier maintenance and development, I think we should unify the naming style of the workspace. I recommend being "template-ws" for the same style as to repo name "ros2-agv-essentials".

2023-10-28 09:36 UTC, j3soon commented on template_ws/README.md
The initial decision to use different naming styles arises from the fact that ros2 packages seem to have a convention of using underscore (`_`), while docker images seem to prefer using hyphen (`-`).

I agree that the current naming style difference of `ros2-agv-essentials` and `template_ws` is less than ideal. However, I'm not entirely sure about the choice of using hyphens instead of underscores for our package names (since it is different than the naming style in ros2). Maybe we can use a workaround for now, and defer this choice to some time in the future?

We can ask the user to use spaces when creating a workspace (e.g., `./scripts/create_workspace.sh "slam toolbox"`), the script can then replace the space to underscore/hyphen (`slam_toolbox`/`slam-toolbox`) afterwards.

What do you think?

2023-10-28 09:58 UTC, YuZhong-Chen commented on template_ws/README.md
Okay, I think it fine to use the workaround for now.
Thank you very much.

2023-10-28 12:26 UTC, j3soon requested changes

2023-10-28 12:26 UTC, j3soon commented on template_ws/.gitignore
> +!docker/cache/.gazebo/.gitkeep
This part should be:

```
# Gazebo cache
docker/cache/*
!docker/cache/.gazebo
docker/cache/.gazebo/*
!docker/cache/.gazebo/.gitkeep
```

as mentioned here: https://github.com/j3soon/ros2-agv-essentials/pull/13#discussion_r1374202127

The correct way to unignore file is rather ugly... The post below explains why this is required:

See: https://stackoverflow.com/a/5534865

2023-10-28 12:26 UTC, j3soon commented on scripts/create_workspace.sh
> +# - https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
Consider use the shortened URL by the `Share` feature of Stack Overflow:

https://stackoverflow.com/q/59895

2023-10-28 12:26 UTC, j3soon commented on scripts/create_workspace.sh
> +echo "# ${NEW_WS_NAME_UNDERSCORE}" > ${NEW_WS_DIR}/README.md
Make sure to quote all paths in double quotes `"${NEW_WS_DIR}/..."`.

The current use of `rm -rf ...` may be destructive if the path contains whitespaces.

2023-11-02 07:08 UTC, j3soon approved these changes

2023-11-02 07:08 UTC, merged