Add 3 worlds from AWS Robotics
j3soon/ros2-agv-essentials pull request #6
Opened 2023-08-21 18:00 UTC by ClassLongJoe1112

- 3 worlds: [small warehouse](https://github.com/aws-robotics/aws-robomaker-small-warehouse-world), [small house](https://github.com/aws-robotics/aws-robomaker-small-house-world) and the first floor of a [hospital](https://github.com/aws-robotics/aws-robomaker-hospital-world), are extracted from [AWS Robotics team](https://github.com/aws-robotics).
- 3 2D maps (in `.yaml`) is created using the `tb3_simulation_launch.py` from [nav2_bringup](https://index.ros.org/p/nav2_bringup/) package, which has already included a builtin navigating algorithm and a turtlebot3 (waffle) is used. To produce a map file for the desired world, try:
``` 
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False world:=<world_file> slam:=True
```

2023-09-03 09:21 UTC, j3soon requested changes
Aside from the individual comments, please also:
- Change the directory `map_ws` to `aws_robotics_worlds_ws` for clarity.
- Remove the `build`, `install`, `log` directories.
- Move the `*.pgm` and `*.yaml` files in `map_ws/src/aws_worlds/` to `map_ws/output/`. (They are outputs of a command, not a source file)

Please resolve each comment and re-request a review. Thank you.

P.S. I haven't tested the code & verified the instructions in the README yet. Will test them after the fix.

2023-09-03 09:21 UTC, j3soon commented on map_ws/src/.devcontainer/devcontainer.json
The `build`, `install`, `log` directories won't be necessary if following the devcontainer settings in the template.

Please update the settings according to: https://github.com/j3soon/ros2-agv-essentials/blob/7541daa77726759137159c07ddfdb327dade3edc/template_ws/.devcontainer/devcontainer.json

2023-09-03 09:21 UTC, j3soon commented on map_ws/src/.devcontainer/Dockerfile
Please clean up the Dockerfile according to the template. For example, `ARG USERNAME=USERNAME` should be `ARG USERNAME=user`.

See: https://github.com/j3soon/ros2-agv-essentials/blob/7541daa77726759137159c07ddfdb327dade3edc/template_ws/.devcontainer/Dockerfile

2023-09-03 09:21 UTC, j3soon commented on map_ws/src/aws_worlds/hospital/aws_hospital.world
I'm not sure why the `.world` file should be included here. Since we are using git submodules, I think we don't need an extra copy of the world file?

The same case applies to the `house` and `warehouse` world files.

2023-09-23 08:12 UTC, ClassLongJoe1112 commented
I resolved the issues according to @j3soon's [suggestions](https://github.com/j3soon/ros2-agv-essentials/pull/6#pullrequestreview-1608460548). In addition, I adjusted the mounting path (`"workspaceMount"`) of the docker container in `.devcontainer/devcontainer.json`, just like​ the `template_ws` written by @j3soon and @YuZhong-Chen.

2023-10-03 16:26 UTC, j3soon requested changes
Please resolve each comment, test the instructions on the latest commit, and re-request a review. Thank you.

2023-10-03 16:26 UTC, j3soon commented on aws_robotics_worlds_ws/.devcontainer/Dockerfile
Directly copy the dockerfile from the latest template: https://github.com/j3soon/ros2-agv-essentials/blob/master/template_ws/docker/Dockerfile

2023-10-03 16:26 UTC, j3soon commented on aws_robotics_worlds_ws/.devcontainer/devcontainer.json
Copy `devcontainer.json` from template, and modify accordingly:

https://github.com/j3soon/ros2-agv-essentials/tree/master/template_ws/.devcontainer

Please also add the `docker-compose.yaml` file.

2023-10-11 14:43 UTC, j3soon requested changes

2023-10-11 14:43 UTC, j3soon commented on aws_robotics_worlds_ws/docker/docker-compose.yaml
I'm not sure why this file is empty. See: https://github.com/j3soon/ros2-agv-essentials/blob/54ed823c2ccb3063c1c287a5bbe45787ffec311d/template_ws/docker/docker-compose.yaml

I don't think the current docker environment can work without this file. Please test your instructions on the latest commit before re-requesting review.

2023-10-11 14:43 UTC, j3soon commented on aws_robotics_worlds_ws/README.md
Briefly mention that `small_warehouse.world` can be replaced with `hospital.world`.

It would be even better (but optional) if you could include detailed instructions for the hospital environment, and add corresponding screenshots.

2023-10-11 14:43 UTC, j3soon commented on aws_robotics_worlds_ws/output/house/aws_house.world
I'm not sure why the `.world` file should be included here. Since we are using git submodules, I think we don't need an extra copy of the world file?

2023-10-11 14:43 UTC, j3soon commented on aws_robotics_worlds_ws/output/house/aws_house.pgm
Also add the `.pgm` and `.yaml` files for the hospital environment.

2023-10-11 14:43 UTC, j3soon commented on aws_robotics_worlds_ws/output/house/aws_house.pgm
If I'm not mistaken, the `aws_house.pgm` and `aws_house.yaml` file should be `warehouse.pgm` and `warehouse.yaml`. Please regenerate these files based on the warehouse/hospital environment.

2023-10-21 12:11 UTC, ClassLongJoe1112 commented on aws_robotics_worlds_ws/README.md
Is there any better naming rule for the images or it doesn't matter? Because if I sorted the images as `image1`, `image2`, ... according to the order they are shown in `README.md`, it will be exhausting to rename them again when a new image needs to be added.

2023-10-21 13:23 UTC, j3soon commented on aws_robotics_worlds_ws/README.md
Yes.

You can change their file names to something descriptive.

For example, you can change `image2.png` to:
- `gazebo-not-responding`, or
- `02-gazebo-not-responding`

2023-10-21 13:32 UTC, j3soon requested changes
Please:
- Remove unwanted files such as logs.
- Update image names with descriptive file names.

Make sure to resolve all conversations before re-requesting review.

2024-03-11 22:53 UTC, closed without merging